manifests/config.pp, manifests/slave.pp
Remove definition with hostname and use fqdn instead.
Reason : front01.toto and front01.tata have the same hostname
according to facter, resulting in puppet issue
=> fix(hostname): remove hostname from default

Gemfile, Gemfile.lock, Rakefile, spec/spec_helper.rb
It's very handy to have at least just this much of the testing boilerplate to enable easier validation of syntax changes being made to the Puppet files and/or templates.
=> Added minimum framework for tests to enable syntax validation.

manifests/config.pp, manifests/slave.pp, manifests/target.pp
Two small improvements:
1. Respect the configured user when setting file ownership. Makes it possible to change via param.
2. Validate the target names against ^[-_0-9a-zA-Z]+$ to catch any values that Smokeping won't accept - there's a lot more than just spaces unfortunately.
=> Small Improvements

manifests/config.pp
The nodes got a empty color directive on my setup, if i didnt explicitly assign them a color value.
The following fix solves this issue.
=> Fixed error on slave color not beeing automatically generated.

manifests/config.pp
Setting the display name using "slave_display_name" did not work here. The following fix solves this.
=> Fixed error while using slave_display_name (was ignored)

manifests/config.pp, manifests/init.pp
This can be done with something like that:
smokeping::targets:
World:
menu: 'World'
pagetitle: 'Connection to the World'
alerts:
- bigloss
- noloss
GoogleCH:
hierarchy_parent: World
hierarchy_level: 2
menu: google.ch
pagetitle: Google
=> Allow to specify targets through hiera

manifests/install.pp
Hello! Our Puppet run was failing trying to install package `undef` for the perldoc package. It seems there is some confusion as to where parameters are coming from (some from init.pp others from params.pp), for now this fix unblocks us and anyone else trying the module.
Thanks for sharing the module.
PS: Greetings from @darktim
=> perldoc namespace incorrect

manifests/install.pp
Well this is embarrasing... include params *is* needed for the perldoc package to be defined. This is what happens when you edit code directly in github. :disappointed:
=> Include params needed

templates/config.erb
Only include `/etc/smokeping/conf.d/Slaves` when mode is `master`, otherwise that file doesn't exist and smokeping dies with the error:
```
ERROR: can't open /etc/smokeping/config.d/Slaves: No such file or directory
```
=> Only include /etc/smokeping/conf.d/Slaves when mode is master

README.md
Update `README` to match the code in 78dc09deecd0ec61c70e13c44eabcc448028a35c so the alert examples in the docs now work :smile:
=> Fix param name

manifests/apache.pp, manifests/init.pp, metadata.json
Improvement to the original module by using [`puppetlabs/apache`](https://forge.puppet.com/puppetlabs/apache) and [`puppetlabs/firewall`](https://forge.puppet.com/puppetlabs/firewall) to manage the Apache web config and firewall rules respectively. These are controlled by boolean params which default to `false` to retain the original behaviour of this module.
=> Manage Apache

files/local_smokeping.te, manifests/init.pp, metadata.json
Add support to manage an SELinux policy which enables Smokeping to work properly on Red Hat. The new parameter defaults to `false` to retain original behaviour
=> Add support to manage an SELinux policy

manifests/target.pp
With puppet-concat < 2.x, the underlying implementation used lots of
file resources.  That had the side effect that those resources would
automatically depend on the target directory.  However, with 2.x and
later, the concat resources are implemented as a native type, so we need
to add an explicit dependency on the target dir as a result.
=> Concat resources need to depend on target dir

manifests/slave.pp
Fix error for slave instance:
Error: Failed to apply catalog: Parameter content failed on File[/etc/smokeping/slavesecrets.conf]: Munging failed for value 479121 in class content: no implicit conversion of Fixnum into String at /etc/puppetlabs/code/environments/development/modules/smokeping/manifests/slave.pp:29
=> Fix: no implicit conversion of Fixnum into String

manifests/target.pp, templates/target.erb
fixes #74
https://github.com/voxpupuli/puppet-smokeping/pull/70 introduced a
regression.  Several parameters were made mandatory (previously they
defaulted to an empty string.)
They are now `Optional` and default to `undef`.
**This is a breaking change as empty strings are no longer allowed.**
=> Fix smokeping::target type

manifests/init.pp, manifests/params.pp, metadata.json
Currently, master/slave operation isn't supported, so mode should default
to `standalone` for the `RedHat` family.
=> Add EL7 operating systems to metadata.json

manifests/init.pp, metadata.json
In puppet-selinux v1.0.0 source parameter in selinux::module changed to
source_te parameter.
=> Fix selinux::module parameter

metadata.json
Doesn't appear to be any breaking changes going to the latest
version of puppetlabs-apache (v5.5.0 currently), so bump the
upper constraint to `< 6.0.0`.
Fixes #125
=> Support puppetlabs-apache 5.x

metadata.json
Current version is v2.5.0, so bump the deps to support < 3.0.0
Fixes #128
=> Update dependencies to support latest puppetlabs-firewall

manifests/apache.pp, manifests/config.pp, manifests/init.pp, manifests/install.pp, manifests/params.pp, manifests/service.pp, manifests/slave.pp, manifests/target.pp
Convert docs to Puppet Strings format.
Replaces #97.
=> Convert docs to Puppet Strings format

README.md, manifests/apache.pp, manifests/config.pp, manifests/init.pp, manifests/install.pp, manifests/params.pp, manifests/service.pp, manifests/slave.pp, manifests/target.pp
Lint, update wording and links, use standard Puppet formatting.
=> README cleanup

manifests/config.pp
In commit b025f408a6e78fa67c237b453211f29ad4778191 this module was
migrated from params to hiera. Some default params now have became
default undef, but in code we were still testing for default == ''.
=> Fix params that are now default undef

REFERENCE.md, manifests/config.pp, manifests/init.pp, spec/classes/init_spec.rb, templates/targets-header.epp, templates/targets-header.erb
This adds an optional `default_slaves` parameter that sets the `slaves` value at the top level of the `Targets` section of the smokeping config. The top-level `slaves` value is inherited by all of the targets, but can be overridden in individual targets.
Contains #142.
=> Add `default_slaves` parameter for the `Targets` section

REFERENCE.md, manifests/init.pp, manifests/install.pp, spec/classes/init_spec.rb
Allow not managing `imgcache` directory
Add more tests
Fixes #145
=> Add option to manage imgcache directory

REFERENCE.md, manifests/init.pp, manifests/install.pp, metadata.json, spec/classes/init_spec.rb
Rebase of #148.
Also contains #160 and #161.
=> Add option for management of datadir

manifests/install.pp, manifests/slave.pp, metadata.json
The non-namespaced functions are deprecated.
=> Require stdlib 9.x

REFERENCE.md, manifests/config.pp, manifests/init.pp, manifests/slave.pp
Setting slave_name didn't have any affect as this was hard coded to the hosts hostname. Change it to allow setting the slave_name and default to hostname.
=> Fix specifying slave_name
